### PR TITLE
feat: build multi-architecture docker images

### PR DESCRIPTION
**Pull request by gilbsgilbs**
Currently, only `amd64` docker image is built. This commit builds a multi-architecture image and supports many different linux platforms.

Note that I wasn't able to test this. I'm moderately confident that it'll work first try.

### CODE REVIEW

**Comment by powerman** [comment]
I'm going to make a release first, and play with this PR a bit later, because it's harder to test.

**Comment by powerman** [comment]
Well, locally it builds, so… let's try it.

**Comment by powerman** [comment]
The problem is build hangs.
I had same issue on my first try to build it locally, but restart helps and was fast because of using local docker cache.
Restarting on CI doesn't reuse local docker cache for obvious reason, and maybe this somehow related to hang reason.
I'll now re-run CI for the third time, just in case, but it looks like I'll have to revert this commit until you (or someone else) will be able to fix the hang. :disappointed: 
One random guess - it may be related to github throttling Go modules download: each arch's build tries to fetch same Go modules from github in parallel. Maybe using shared docker cache mounted to Go cache dir helps here, or maybe pre-build step with `go mod download` helps… But I don't have time to play with this (and I'm unsure there are enough real users for these docker images anyway).

**Comment by gilbsgilbs** [comment]
Cross-building images can be very slow, but I'm not even able to see the logs of the hanging step. So I don't know if it's actually doing something or not 🤔. Can you access the logs by any chance?

**Comment by gilbsgilbs** [comment]
Yeah, it was just slow, but was eventually successful: https://github.com/powerman/dockerize/actions/runs/4297435102/jobs/7490823537 .

The latest tag is multi-arch: https://hub.docker.com/layers/powerman/dockerize/latest/images/sha256-b70b7c0850b76cdbaf67294ac81249ca64aee521c7cc0169e485af84cb305861 🎉

**Comment by powerman** [comment]
18 minutes… Okay, let's hope it wasn't hang, just I was too impatient.

**Pull request merged**
